version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: carros
      MYSQL_USER: manuela
      MYSQL_PASSWORD: manuela24
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: